## Python Numpy 

In [14]:
import numpy as np 

## create array using numpy 
# Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) 
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [18]:
arr2= np.array([1,2,3,4,5,6,7,8])
arr2.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
#Lets create numpy arry list 
array1 = np.arange(0,100,2).reshape(5,10)
array1

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [35]:
array1[0:3,0:5]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48]])

In [45]:
# this formate retrite specific colloumns form the list 

array1[[1,2,3,4]]

array([[20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [47]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
arr1 =np.array([1,2,3,4,5,6,7])
arr2=np.array([10,12,13,13,12,13,24])

print("Addition", arr1+arr2)
print("Multiplication", arr1 * arr2)

Addition [11 14 16 17 17 19 31]
Multiplication [ 10  24  39  52  60  78 168]


In [59]:
#Universel Function 
arr= np.array([2,3,4,5,6,7,3])
print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 1.73205081]


In [60]:
## Exponential 
print(np.exp(arr))

[   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843   20.08553692]


In [61]:
print(np.log(arr))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 1.09861229]


In [66]:
print(np.mean(arr))
print(np.max(arr))
print(np.average(arr))
print(np.median(arr))


4.285714285714286
7
4.285714285714286
4.0


In [71]:
arr1[3]

np.int64(5)

In [75]:
arr1= np.arange(0,100,1).reshape(10,10)
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
print(arr1[1,4] + arr1[1,5])

29


In [86]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
arr1[7:10,8:10]

array([[78, 79],
       [88, 89],
       [98, 99]])

In [85]:
print(arr1[0,1])

1


In [98]:
# Modify the array elements 
arr1[1,4]= 0
print(arr1)

[[   0    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13    0   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43 1234   45   46   47   48   49]
 [  50   51   52   53   54   55   56   57   58   59]
 [  60   61   62   63   64   65   66   67   68   69]
 [  70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89]
 [  90   91   92   93   94   95   96   97   98   99]]


In [99]:
if 1234 in arr1:
    index = np.where(arr1 == 1234)[0][0]  # Find the index of the first occurrence
    print(f'Element found at index: {index}')


Element found at index: 4


In [100]:
# Statestical concept ---Normalizetion
data= np.array([1,2,3,4,5,12,23,13])

In [103]:
means= np.mean(data)
std = np.std(data)
variance= np.var(data)
print(np.mean(data))
print(np.std(data))
print(np.var(data))

7.875
7.0787975673838845
50.109375


In [132]:
## logical Operetions 
data= np.array([1,2,3,4,5,6,7,8,9,10]).reshape(5,2)
data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [140]:
data[[2,3,1]].reshape(1,6)

array([[5, 6, 7, 8, 3, 4]])